-- Solva · Pedidos (registro manual desde #admin → Despachos)
-- Ejecutar UNA VEZ en el SQL Editor de Supabase.
-- Venta 100% manual: sin bot, sin cotizaciones automáticas. El admin
-- registra el pedido a mano y le hace seguimiento de estado.

create table if not exists public.orders (
  id             uuid        default gen_random_uuid() primary key,
  status         text        not null default 'pending',   -- pending|dispatched|delivered|problem|cancelled
  source         text        not null default 'manual',
  phone          text        not null,
  customer_name  text,
  city           text,
  neighborhood   text,
  address        text,
  apt_ref        text,
  payment_method text,
  recipient_name text,
  items          text        not null,   -- ej: "Producto A(talla M)x1, Producto B x2"
  notes          text,
  admin_notes    text,
  delivery_notes text,
  subtotal       numeric,
  total          numeric,
  hidden         boolean     not null default false,
  order_number   bigint      generated by default as identity,
  created_at     timestamptz default now()
);

-- Lectura/escritura solo para el admin logueado (RLS: authenticated).
alter table public.orders enable row level security;

drop policy if exists "orders_auth_read"  on public.orders;
drop policy if exists "orders_auth_write" on public.orders;
create policy "orders_auth_read"  on public.orders for select to authenticated using (true);
create policy "orders_auth_write" on public.orders for all    to authenticated using (true) with check (true);

-- Realtime opcional para que Despachos refleje cambios en vivo entre pestañas.
alter publication supabase_realtime add table public.orders;
